language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "python setup.py develop"
  - "pip install ."
  - "coverage run --source=smalluuid pip install pytest coveralls"
script: py.test
after_success: coveralls
